### ISSUE TITLE
How to add more spaces?

### ISSUE THREAD

**Issue by visualcookie** [pendo324/EssentialNowPlaying#12]
Hello,

I have sometimes some incredibly large title names and artists. Your application adds 1 space default. Is it possible to add some more space user based? Would be amazing!

**Comment by livejamie** [comment]
Yeah it would be nice to configure the output

**Comment by pendo324** [comment]
Spaces option has been added, let me know if you want anymore configuration of the output. Maybe I'll add some sort of tokenized string to the settings if there is enough demand.
