### ISSUE TITLE
Google Play Not in Dropdown

### ISSUE THREAD

**Issue by livejamie** [pendo324/EssentialNowPlaying#16]
The Essential Now Playing Desktop app doesn't have Google Play in the dropdown in players or settings.

**Comment by livejamie** [comment]
Looks like it just needs to be added in SourceManager.cs

**Comment by pendo324** [comment]
Should be taken care of now, let me know if there are any other issues. Admittedly, it has been a while since I looked at this project (busy with new job) so I might have messed something up.
