### ISSUE TITLE
.exe files missing

### ISSUE THREAD

**Issue by JimmyTheCannon** [pendo324/EssentialNowPlaying#36]
I downloaded the zip file and I can't find either NativeMessagingInterface.exe or Essential Now Playing.exe in it.

**Comment by IranEG** [comment]
Hello,
In the main project page if you click on releases:
![image](https://cloud.githubusercontent.com/assets/10100649/23826316/2bbaaedc-0668-11e7-884d-ba67836e707a.png)

it will take you to the releases page where you'll be able to download the zip file called "Release.zip" which includes the latest build.
![image](https://cloud.githubusercontent.com/assets/10100649/23826343/b73a215e-0668-11e7-8c20-7c293c06ff56.png)

If there are any more issues let us know.

**Comment by JimmyTheCannon** [comment]
Ah, thank you. My apologies, first time using GitHub.
