### ISSUE TITLE
Nothing happens on running EssentialNowPlaying

### ISSUE THREAD

**Issue by JimmyTheCannon** [pendo324/EssentialNowPlaying#37]
When I run the .exe file, nothing happens. Initially Windows asked me if I was certain I wanted to run it because it was an unknown publisher. I told it to run it. Nothing happened. Checked the task manager, can't find the program running. Tried running it again and absolutely nothing happened.

**Comment by briananthony** [comment]
Right click Essential Now Playing.exe and run as administrator.

**Comment by JimmyTheCannon** [comment]
That did it - thanks!
