### ISSUE TITLE
Chrome with Soundcloud displays as "Paused"

### ISSUE THREAD

**Issue by BNMotive** [pendo324/EssentialNowPlaying#39]
I followed instructions and all I seem to get from the addon is a "Paused" message. OBS does display the same thing so it's working. I'd humbly appreciate the help.

**Comment by pendo324** [comment]
hey @BNMotive, thanks for reporting the issue. It is due to Soundcloud's new layout. Its a pretty simple fix, so I'll try to push an update for the browser extension either tomorrow (Friday) or some time this weekend.

**Comment by BNMotive** [comment]
Thank you very much sir, IO appreciate your work, makes my channel look nice and organized.

**Comment by pendo324** [comment]
@BNMotive I just published the update on the Chrome Marketplace, your extension should update in about an hour. Let me know if it works!

**Comment by BNMotive** [comment]
I get an app crash and error message that says "Native Messaging Interface has stopped working." the add-on does say the name of the song though
