### ISSUE TITLE
Google Play not on the Dropdown

### ISSUE THREAD

**Issue by hanmun** [pendo324/EssentialNowPlaying#40]
I was able to have the plugin installed and working perfectly with Youtube but the problem is I needed it for Google Play and that option is nowhere to be found in the Desktop Application. I've seen other people bring this up and supposedly it has been fixed? I've re-downloaded the plugin, updated my Chrome Extension but still nothing :(

**Comment by hanmun** [comment]
Edit: I accidentally downloaded the wrong release but now I've downloaded the correct one and Google Play is indeed in the dropbown. However, as soon as I run the program it says NativeMessagingInterface.exe has stopped working.

**Comment by pendo324** [comment]
@hanmun Hey, if you have some time could you:
1. Close the Essential Now Playing desktop application
2. Open up task manager and end the "NativeMessagingInterface" process
3. Try running Essential Now Playing again and using the Google Play option

Let me know if you have any questions or if some of my instructions don't make sense. Thanks!

**Comment by hanmun** [comment]
@pendo324 Thanks for the reply! I actually figured everything out. I did what you just described and relaunched the app and it's working now, thank you so much!
