### ISSUE TITLE
Youtube Update

### ISSUE THREAD

**Issue by thewhiteboardist** [pendo324/EssentialNowPlaying#53]
New youtube update makes Now Playing Companion read "No Song Playing" on any video.  Net code tree must have changed.

**Comment by pendo324** [comment]
@thewhiteboardist I’ll check it out this weekend. Most likely I will push an update to the extension, so you won’t have to redownload the desktop app :)

**Comment by pendo324** [comment]
Thank you for notifying me!

**Comment by thewhiteboardist** [comment]
Thanks for the quick reply!

**Comment by pendo324** [comment]
Quick update: as expected, its just a one line change to the extension. I actually made the change a couple days ago, but the chrome webstore wasn't letting me upload the update for some reason. I'll check it out when I get home.

**Comment by thewhiteboardist** [comment]
Sweet. Thanks

On Mar 5, 2018 1:58 PM, "Justin" <notifications@github.com> wrote:

Quick update: as expected, its just a one line change to the extension. I
actually made the change a couple days ago, but the chrome webstore wasn't
letting me upload the update for some reason. I'll check it out when I get
home.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pendo324/EssentialNowPlaying/issues/53#issuecomment-370562945>,
or mute the thread

**Comment by JulianHa** [comment]
Same issue over here, doesn't seem to work what so ever.

**Comment by pendo324** [comment]
Took me a bit longer than I said, but I got it done! Let me know if you experience any more issues with Youtube.

**Comment by thewhiteboardist** [comment]
Will the fix auto update the extension or do I need to update the program?

**Comment by pendo324** [comment]
The extension should auto-update. No need to update the program.
