### ISSUE TITLE
No more Chrome Extension

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [pendo324/EssentialNowPlaying#65]
Hi , The extension is no more on the google chrome extension webstore ... so sad :(

**Comment by pendo324** [comment]
Sorry about that. I'm working on getting it back up. It was taken down because a "promotional image" is now required on the Chrome Webstore, and I did not upload one originally.

**Comment by pendo324** [comment]
I have resubmitted the extension and it is undergoing manual review, which may take several business days. I'll keep this thread updated.

**Comment by TomAvecLeVdsl** [comment]
Ok thanks 🙂
