### ISSUE TITLE
Adding to OBS?

### ISSUE THREAD

**Issue by grumblepig** [pendo324/EssentialNowPlaying#8]
Hello, I can get the song name in the app, but I'm, not sure how to put that onto OBS. Can I get a quick guide in doing this?

**Comment by pendo324** [comment]
Sure. Which version of OBS are you using?

**Comment by grumblepig** [comment]
It's the standard OBS, not multiplat or studio

**Comment by pendo324** [comment]
So, I don't have the original OBS installed at the moment, but the steps should be similar.

You're going to want to right click under "Sources" and then "Add Text Source". (you could also press the "+" symbol to add the text source).

Now, under the "Text File" option, you're going to search for the text file that you specified in EssentialNowPlaying. You can then move it on screen or w/e you want. The file will be updated with the "Now Playing" song that is also shown on in program preview.

If you need any more help, just let me know.

**Comment by queenie1738** [comment]
im currently using obs studio and would like to use this program. ive downloaded it and just need a walkthrough of how to get it going.

**Comment by danando101** [comment]
cant display on OBS, i dont get a text file -.- help

**Comment by xfunnypigx** [comment]
![image](https://cloud.githubusercontent.com/assets/19739850/20172032/b3367722-a733-11e6-994c-5424cdaf4066.png)
Use the browsing tab, then follow Jalva304's advice.

> So, I don't have the original OBS installed at the moment, but the steps should be similar.
>
>You're going to want to right click under "Sources" and then "Add Text Source". (you could also press the >"+" symbol to add the text source).
>
>Now, under the "Text File" option, you're going to search for the text file that you specified in >EssentialNowPlaying. You can then move it on screen or w/e you want. The file will be updated with the >"Now Playing" song that is also shown on in program preview.
>
>If you need any more help, just let me know.
