### ISSUE TITLE
Song cover art as an option 

### ISSUE THREAD

**Issue by chazragg** [pendo324/EssentialNowPlaying#9]
Is there a way to obtain the cover art form spotify web player ? i have seen programs do it but this is from the windows app which i dont use. i did do some lookign around but i see some people say you cant and other say you can 

http://stackoverflow.com/questions/10123804/retrieve-cover-artwork-using-spotify-api here is a possible way to add it but i am 100% sure not being a developer

**Comment by pendo324** [comment]
Closed in favor of #11
